Repository dnestorovic/DormService, pull requests merged in 2024-06, with the labels that each got.

#74 Add manageable machines fetch
  DormService/Services/Laundry/Laundry.API/Controllers/WashinhMachineManagementController.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/IWashingMachineManagementRepository.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/WashingMachineManagementRepository.cs
Labels: enhancement

#76 Add managable machines delete
  DormService/Services/Laundry/Laundry.API/Controllers/WashinhMachineManagementController.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/IWashingMachineManagementRepository.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/WashingMachineManagementRepository.cs
Labels: enhancement

#96 Add support for grpc communication with Payment service
  DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs
  DormService/Services/Laundry/Laundry.API/GrpcServices/PaymentGrpcService.cs
  DormService/Services/Laundry/Laundry.API/Laundry.API.sln
  DormService/Services/Laundry/Laundry.API/Laundry.csproj
  DormService/Services/Laundry/Laundry.API/Program.cs
  DormService/Services/Payment/Payment.GRPC/Dockerfile
  DormService/docker-compose.override.yml
  DormService/docker-compose.yml
Labels: enhancement

#102 Initialize frontend project
  DormService/DormApps/dorm-spa/.gitignore
  DormService/DormApps/dorm-spa/README.md
  DormService/DormApps/dorm-spa/package.json
  DormService/DormApps/dorm-spa/public/index.html
  DormService/DormApps/dorm-spa/public/manifest.json
  DormService/DormApps/dorm-spa/public/robots.txt
  DormService/DormApps/dorm-spa/src/Apps/App.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/LandingPage.tsx
  DormService/DormApps/dorm-spa/src/index.tsx
  DormService/DormApps/dorm-spa/src/react-app-env.d.ts
  DormService/DormApps/dorm-spa/src/reportWebVitals.ts
  DormService/DormApps/dorm-spa/src/setupTests.ts
  DormService/DormApps/dorm-spa/tsconfig.json
  DormService/DormApps/dorm-spa/yarn.lock
Labels: enhancement, good first issue

#99 Implemet machine suggestions API call
  DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs
  DormService/Services/Laundry/Laundry.API/Entities/WashingMachineConfiguration.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/IWashingMachineManagementRepository.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesManagement/WashingMachineManagementRepository.cs
  DormService/docker-compose.override.yml
Labels: enhancement

#105 Add landing page and banner
  DormService/DormApps/dorm-spa/package-lock.json
  DormService/DormApps/dorm-spa/package.json
  DormService/DormApps/dorm-spa/public/assets/reception-banner.png
  DormService/DormApps/dorm-spa/public/index.html
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/LandingPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/components/Banner.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/components/Login.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/design/banner.scss
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/design/login.scss
  DormService/DormApps/dorm-spa/yarn.lock
Labels: enhancement

#111 Add Side Menu Componnet and Navigation
  DormService/DormApps/dorm-spa/public/assets/cloth.png
  DormService/DormApps/dorm-spa/public/assets/documentation-icon.png
  DormService/DormApps/dorm-spa/public/assets/food-icon.png
  DormService/DormApps/dorm-spa/public/assets/food-icon2.png
  DormService/DormApps/dorm-spa/public/assets/food-icon3.png
  DormService/DormApps/dorm-spa/public/assets/green-triangle-pattern.jpg
  DormService/DormApps/dorm-spa/public/assets/green-triangle-pattern2.jpg
  DormService/DormApps/dorm-spa/public/assets/payment-icon.png
  DormService/DormApps/dorm-spa/public/assets/user.png
  DormService/DormApps/dorm-spa/src/Apps/App.tsx
  DormService/DormApps/dorm-spa/src/Apps/CanteenPage/CanteenPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentationPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/components/Banner.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/components/Login.tsx
  DormService/DormApps/dorm-spa/src/Apps/LandingPage/design/login.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/LaudnryPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/PaymentPage.tsx
  DormService/DormApps/dorm-spa/src/components/PageLayout/PageLayout.tsx
  DormService/DormApps/dorm-spa/src/components/PageLayout/page-layout.scss
  DormService/DormApps/dorm-spa/src/components/SideMenu/SideMenu.tsx
  DormService/DormApps/dorm-spa/src/components/SideMenu/side-menu.scss
  DormService/DormApps/dorm-spa/src/design/colors.scss
  DormService/DormApps/dorm-spa/src/design/design-ui.scss
Labels: enhancement

#88 feat: Add document Controller to Documentation service
  DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentController.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
Labels: enhancement

#89 feat: Add Documentation List Controller to Documentation service
  DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Repositories/Interfaces/DocumentationListRepository.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Repositories/Interfaces/IDocumentationListRepository.cs
Labels: enhancement

#131 Implement log out method on Security service
  DormService/Security/IdentityServer/Controllers/AuthenticationController.cs
Labels: enhancement

#120 Add modals and test them on the laundry page
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/LaudnryPage.tsx
  DormService/DormApps/dorm-spa/src/components/Modals/ModalDialog.tsx
  DormService/DormApps/dorm-spa/src/components/Modals/modal-dialog.scss
  DormService/DormApps/dorm-spa/src/design/design-ui.scss
  DormService/DormApps/dorm-spa/src/index.tsx
Labels: enhancement

#126 Add base service
  DormService/DormApps/dorm-spa/src/services/BaseService.ts
Labels: enhancement, good first issue

#123 Create pop up notifications
  DormService/DormApps/dorm-spa/public/assets/white-triangle-pattern.jpg
  DormService/DormApps/dorm-spa/src/Utils/StringUtils.ts
  DormService/DormApps/dorm-spa/src/components/Notifications/Notification.tsx
  DormService/DormApps/dorm-spa/src/components/Notifications/notification.scss
  DormService/DormApps/dorm-spa/src/design/colors.scss
  DormService/DormApps/dorm-spa/src/design/design-ui.scss
Labels: enhancement

#137 Add method protection in Payment service
  DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs
  DormService/Services/Payment/Payment.API/Payment.API.csproj
  DormService/Services/Payment/Payment.API/Program.cs
  DormService/Services/Payment/Payment.API/appsettings.Development.json
Labels: enhancement

#140 Laundry service cleanup
  DormService/Services/Laundry/Laundry.API/Controllers/WashingMachineController.cs
  DormService/Services/Laundry/Laundry.API/Entities/DTOs/WashingMachineCofigurationDTO.cs
  DormService/Services/Laundry/Laundry.API/Entities/DTOs/WashingMachineReservationDTO.cs
  DormService/Services/Laundry/Laundry.API/Entities/WashingMachine.cs
  DormService/Services/Laundry/Laundry.API/Entities/WashingMachineConfiguration.cs
  DormService/Services/Laundry/Laundry.API/Program.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/IWashingMachineRepository.cs
  DormService/Services/Laundry/Laundry.API/Repository/WashingMachinesReservations/WashingMachineRepository.cs
Labels: bug

#141 fix: fix bug in delete document endpoint and refactor code
  DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Data/DocumentContext.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Documentation.API.csproj
  DormService/Services/Documentation/Documentation.API/Documentation.API/Entities/Document.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Entities/DocumentationList.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Repositories/Interfaces/DocumentationListRepository.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Repositories/Interfaces/IDocumentationListRepository.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/appsettings.json
Labels: bug

#142 Implement laundry fe page
  DormService/DormApps/dorm-spa/public/assets/promo.gif
  DormService/DormApps/dorm-spa/public/assets/washing-machine.png
  DormService/DormApps/dorm-spa/public/assets/watch.png
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/LaudnryPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/AlreadyReservedMachinesCard/AlreadyReservedMachinesCard.tsx
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/AlreadyReservedMachinesCard/student-reserved-machines-card.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/DiscountWashingMachinesTable/DiscountWashingMachinesTable.tsx
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/DiscountWashingMachinesTable/discount-machines.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/DropdownMenu/DropdownMenu.tsx
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/DropdownMenu/dropdown-menu.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/WashingMachineReservationModal/WashingMachineReservationModal.tsx
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/WashingMachineReservationModal/reservation-dialog.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/WashingMachinesTable/WashingMachinesTable.tsx
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/components/WashingMachinesTable/washing-machines-table.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/laundry-page.scss
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/models/WashingMachine.ts
  DormService/DormApps/dorm-spa/src/Apps/LaundryPage/services/UserReservationsService.ts
  DormService/DormApps/dorm-spa/src/components/Modals/modal-dialog.scss
  DormService/DormApps/dorm-spa/src/components/PageLayout/page-layout.scss
  DormService/DormApps/dorm-spa/src/design/design-ui.scss
  DormService/DormApps/dorm-spa/src/services/BaseService.ts
Labels: enhancement

#148 Cover all cases for every method in controller
  DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs
  DormService/Services/Payment/Payment.Common/Entities/StudentDebts.cs
  DormService/Services/Payment/Payment.Common/Repository/DebtsRepository.cs
Labels: enhancement

#157 feat: Add base version of documentation page and connect it to documentation api
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentForm.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentationPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/document-page.scss
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/models/DocumentModel.ts
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/models/DocumentationListModel.ts
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/services/DocumentationService.ts
  DormService/DormApps/dorm-spa/yarn.lock
  DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
  DormService/Services/Documentation/Documentation.API/Documentation.API/Documentation.API.csproj
  DormService/Services/Documentation/Documentation.API/Documentation.API/Program.cs
Labels: enhancement

#152 Set confirmation dialog for paying
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/PaymentPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/models/DebtsModel.ts
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/payment-page.scss
Labels: enhancement

#161 feat: add logic and style for documentation page
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentForm.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentationPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DropDownMenu.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/GradeDegreeSelection.tsx
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/document-form.scss
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/document-page.scss
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/dropdown-menu.scss
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/services/DocumentationService.ts
  DormService/DormApps/dorm-spa/src/design/design-ui.scss
  DormService/Services/Documentation/Documentation.API/Documentation.API/Controllers/DocumentationListController.cs
Labels: enhancement

#159 Cover one more edge case for reducing credit in gRPC communication
  DormService/Services/Payment/Payment.Common/Repository/DebtsRepository.cs
Labels: bug

#182 Sending email for successfully transaction
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/PaymentPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/services/PaymentService.ts
  DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs
  DormService/Services/Payment/Payment.API/Payment.API.csproj
  DormService/Services/Payment/Payment.API/Program.cs
  DormService/Services/Payment/Payment.API/appsettings.Development.json
Labels: enhancement

#185 Payment cleanup
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/PaymentPage.tsx
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/models/DebtsModel.ts
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/payment-page.scss
  DormService/DormApps/dorm-spa/src/Apps/PaymentPage/services/PaymentService.ts
  DormService/DormApps/dorm-spa/src/Utils/TokenUtil.ts
  DormService/DormApps/dorm-spa/src/services/BaseService.ts
  DormService/DormApps/dorm-spa/src/services/IdentityService.ts
  DormService/Security/IdentityServer/Controllers/AuthenticationController.cs
  DormService/Security/IdentityServer/Controllers/UserController.cs
  DormService/Services/Payment/Payment.API/Controllers/DebtsController.cs
  DormService/Services/Payment/Payment.Common/Data/DebtsContext.cs
  DormService/Services/Payment/Payment.Common/Data/StudentDebtsContextSeed.cs
  DormService/Services/Payment/Payment.Common/Entities/StudentDebts.cs
  DormService/Services/Payment/Payment.Common/Repository/DebtsRepository.cs
  DormService/Services/Payment/Payment.GRPC/Protos/payment.proto
Labels: enhancement

#187 limit input values for point calculation
  DormService/DormApps/dorm-spa/src/Apps/DocumentationPage/DocumentationPage.tsx
Labels: enhancement
